apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/part-of: person-service-chart
spec:
  template:
    metadata:
      name: {{ .Chart.Name | quote }}
    spec:
      restartPolicy: Never
      containers:
        - name: initialize-database
          image: "quay.io/wpernath/kustomize-ubi:v4.4.1"
          env:
            - name: NAMESPACE
              value: {{ .Release.Namespace | default "better-helm" | quote }}
          command: 
          - bin/bash
          - -c
          - |
            SERVICE_URL=person-service.${NAMESPACE}.svc:8080/person
            NUM_PERSONS=$(curl http://$SERVICE_URL/count)

            if [ $NUM_PERSONS -eq 0 ]; then
              echo "There are no persons in the database, filling some"

              http --ignore-stdin --json POST ${SERVICE_URL} firstName=Carlos lastName=Santana salutation=Mr
              http --ignore-stdin --json POST ${SERVICE_URL} firstName=Joe lastName=Cocker salutation=Mr
              http --ignore-stdin --json POST ${SERVICE_URL} firstName=Eric lastName=Clapton salutation=Mr
              http --ignore-stdin --json POST ${SERVICE_URL} firstName=Kurt lastName=Cobain salutation=Mr

            else
              echo "There are already $NUM_PERSONS persons in the database."
              http --ignore-stdin ${SERVICE_URL} 
            fi
