auth:
    username: wanja
    password: wanja
    database: wanjadb

volumePermissions:
    enabled: false
    securityContext:
        runAsUser: "auto"

securityContext:
    enabled: false
    runAsUser: "auto"
    fsGroup: ""


containerSecurityContext:
    enabled: false

shmVolume:
    chmod:
        enabled: false
